
resolver: lts-22.27

ghc-options:
  "$locals": >-
    -fwrite-ide-info
    -hiedir .hie
    -dumpdir .ghcdump
    -Wredundant-constraints

nix:
  pure: false
  packages:
  - pcre
  - pkg-config
  - zlib

packages:
- ./sandwich
- ./sandwich-contexts
- ./sandwich-contexts-docker
- ./sandwich-contexts-kubernetes
- ./sandwich-contexts-minio
- ./sandwich-hedgehog
- ./sandwich-quickcheck
- ./sandwich-slack
- ./sandwich-webdriver

- ./sandwich-demos

- ./demos/demo-basic
- ./demos/demo-command-line-args
- ./demos/demo-contexts
- ./demos/demo-context-dependencies
- ./demos/demo-context-nested
- ./demos/demo-custom-exceptions
- ./demos/demo-discover
- ./demos/demo-fake-smtp-server
- ./demos/demo-golden
- ./demos/demo-hedgehog
- ./demos/demo-kubernetes-kind
- ./demos/demo-kubernetes-longhorn
- ./demos/demo-kubernetes-minikube
- ./demos/demo-kubernetes-seaweedfs
- ./demos/demo-landing
- ./demos/demo-minio
- ./demos/demo-nix-binary
- ./demos/demo-paralleln
- ./demos/demo-postgres
- ./demos/demo-processes
- ./demos/demo-quickcheck
- ./demos/demo-setup-teardown
- ./demos/demo-slack
- ./demos/demo-stack-test
- ./demos/demo-timing
- ./demos/demo-timing-parallel
- ./demos/demo-tui
- ./demos/demo-webdriver
- ./demos/demo-webdriver-landing
- ./demos/demo-webdriver-pool
- ./demos/demo-webdriver-positioning
- ./demos/demo-webdriver-video

extra-deps:
- vty-windows-0.2.0.0

## For sandwich-contexts

- git: https://github.com/codedownio/minio-hs
  commit: 1e63a0ec44fff374799b25a0a02c041eab664c4f

## For sandwich-contexts-docker

- git: https://github.com/codedownio/docker-openapi.git
  commit: 8cf2e348999c6f8cf2bb2583b4f5f083fba5170c

## For sandwich-contexts-kubernetes

- git: https://github.com/codedownio/kubernetes-client-haskell.git
  # codedown-feb-2024
  commit: 82f233c98f7124786c689c2407e84b1b94dba32f
  subdirs:
  - kubernetes
  - kubernetes-client

- git: https://github.com/codedownio/haskell-oidc-client
  # codedown-jan-2024-ghc96
  commit: 4c122412e80c45bd28d03ead16f1a153bd53fcf4

# https://github.com/kubernetes-client/haskell/issues/64
# https://github.com/channable/vaultenv/issues/99
- git: https://github.com/codedownio/hs-certificate
  # codedown-feb-2024
  # This branch
  # 1. Takes akshaymankar's fixes from https://github.com/haskell-tls/hs-certificate/pull/113
  # and rebases them on the most recent https://github.com/haskell-tls/hs-certificate master branch
  # 2. Cherry-picks kazuyamamoto's commit switching the package tocrypton, from here:
  # https://github.com/kazu-yamamoto/crypton-certificate/commit/c11bbbeec2360ce797c5eb3bd4953cbc5bf1a0d6
  commit: dcd0d5b200e96e90c6daa728585c23be5309a955
  subdirs:
  - x509-validation
