name:                demo-webdriver-pool
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- filepath
- resource-pool
- sandwich
- sandwich-webdriver
- string-interpolate
- unliftio
- unliftio-core
- webdriver

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  demo-webdriver-pool:
    main: Main.hs
    source-dirs: app
