name:                sandwich
version:             0.1.5.1
github:              "codedownio/sandwich"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"
copyright:           "2023 Tom McLaughlin"
category:            Testing
homepage:            https://codedownio.github.io/sandwich
synopsis:            Yet another test framework for Haskell
description:         Please see the <https://codedownio.github.io/sandwich documentation>.

extra-source-files:
- CHANGELOG.md

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- ViewPatterns

dependencies:
- aeson
- ansi-terminal
- async
- base >= 4.11 && < 5
- colour
- containers
- bytestring
- deepseq
- directory
- exceptions
- filepath
- free
- lifted-async
- microlens
- microlens-th
- monad-control
- monad-logger
- mtl
- optparse-applicative
- pretty-show
- process
- safe
- safe-exceptions
- stm
- string-interpolate
- text
- time
- transformers
- transformers-base
- unliftio-core
- vector

# For spec discovery. Move to its own package?
- template-haskell
- haskell-src-exts

when:
- condition: "!os(windows)"
  dependencies:
  - brick
  - unix
  - vty

library:
  source-dirs: src
  ghc-options:
  - -W
  exposed-modules:
  - Test.Sandwich
  - Test.Sandwich.Contexts
  - Test.Sandwich.Expectations
  - Test.Sandwich.Golden
  - Test.Sandwich.Logging
  - Test.Sandwich.Misc
  - Test.Sandwich.Nodes
  - Test.Sandwich.Options
  - Test.Sandwich.Formatters.FailureReport
  - Test.Sandwich.Formatters.LogSaver
  - Test.Sandwich.Formatters.Print
  - Test.Sandwich.Formatters.Silent
  - Test.Sandwich.Internal
  - Test.Sandwich.TH
  when:
  - condition: "os(windows)"
    dependencies:
    - Win32
  - condition: "!os(windows)"
    source-dirs: unix-src
    exposed-modules:
    - Test.Sandwich.Formatters.TerminalUI
    other-modules:
    - Test.Sandwich.Formatters.TerminalUI.AttrMap
    - Test.Sandwich.Formatters.TerminalUI.CrossPlatform
    - Test.Sandwich.Formatters.TerminalUI.Draw
    - Test.Sandwich.Formatters.TerminalUI.Draw.ColorProgressBar
    - Test.Sandwich.Formatters.TerminalUI.Draw.ToBrickWidget
    - Test.Sandwich.Formatters.TerminalUI.Draw.TopBox
    - Test.Sandwich.Formatters.TerminalUI.Draw.Util
    - Test.Sandwich.Formatters.TerminalUI.Filter
    - Test.Sandwich.Formatters.TerminalUI.Keys
    - Test.Sandwich.Formatters.TerminalUI.OpenInEditor
    - Test.Sandwich.Formatters.TerminalUI.Types

executables:
  sandwich-demo:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich

  sandwich-discover:
    main: Main.hs
    source-dirs:
    - discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich

  sandwich-test:
    main: Main.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich

tests:
  sandwich-test-suite:
    main: Main.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich
