name:                demo-hedgehog
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- hedgehog
- sandwich
- sandwich-hedgehog
- string-interpolate

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  demo-hedgehog:
    main: Main.hs
    source-dirs: app
