name:                demo-setup-teardown
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- lifted-base
- monad-logger
- sandwich
- string-interpolate

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  demo-basic:
    main: Main.hs
    source-dirs: app
