name: sandwich-contexts-kubernetes
version: 0.1.0.0
synopsis: CodeDown test contexts
description: Please see README.md
author: Tom McLaughlin
maintainer: tom@codedown.io
copyright: 2024 Tom McLaughlin
dependencies:
- base
- containers
- sandwich
- unliftio

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- LambdaCase
- MultiWayIf
- ViewPatterns
- TupleSections
- FlexibleContexts
- NoImplicitPrelude
- NumericUnderscores

ghc-options:
- -Wunused-packages
- -Wall
# - -Wpartial-fields
# - -Wredundant-constraints # Reports HasCallStack, so keep it off normally

library:
  source-dirs: lib
  exposed-modules:
  - Sandwich.Contexts.Kubernetes.Cluster
  - Sandwich.Contexts.Kubernetes.KindCluster
  - Sandwich.Contexts.Kubernetes.MinikubeCluster
  - Sandwich.Contexts.Kubernetes.MinioOperator
  - Sandwich.Contexts.Kubernetes.MinioS3Server
  - Sandwich.Contexts.Kubernetes.Namespace
  - Sandwich.Contexts.Kubernetes.SeaweedFS
  - Sandwich.Contexts.Kubernetes.Types
  dependencies:
  - aeson
  - base64-bytestring
  - bytestring
  - sandwich-contexts
  - containers
  - exceptions
  - filepath
  - hostname
  - http-client
  - kubernetes-client
  - kubernetes-client-core
  - lens
  - lens-regex-pcre
  - lifted-base
  - minio-hs
  - monad-control
  - monad-logger
  - mtl
  - network
  - network-uri
  - process
  - random
  - relude
  - retry
  - safe
  - string-interpolate
  - temporary
  - text
  - unliftio-core
  - vector
  - yaml
