name: sandwich-contexts-kubernetes
version: 0.1.0.0
synopsis: CodeDown test contexts
description: Please see README.md
author: Tom McLaughlin
maintainer: tom@codedown.io
copyright: 2024 Tom McLaughlin
dependencies:
- base
- sandwich

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- LambdaCase
- MultiWayIf
- ViewPatterns
- TupleSections
- FlexibleContexts
- NoImplicitPrelude
- NumericUnderscores

ghc-options:
- -Wunused-packages
- -Wall
# - -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: lib
  exposed-modules:
  - Test.Sandwich.Contexts.Kubernetes.Cluster
  - Test.Sandwich.Contexts.Kubernetes.Images
  - Test.Sandwich.Contexts.Kubernetes.KindCluster
  - Test.Sandwich.Contexts.Kubernetes.KindCluster.Images
  - Test.Sandwich.Contexts.Kubernetes.Kubectl
  - Test.Sandwich.Contexts.Kubernetes.Longhorn
  - Test.Sandwich.Contexts.Kubernetes.MinikubeCluster
  - Test.Sandwich.Contexts.Kubernetes.MinikubeCluster.Images
  - Test.Sandwich.Contexts.Kubernetes.MinioOperator
  - Test.Sandwich.Contexts.Kubernetes.MinioS3Server
  - Test.Sandwich.Contexts.Kubernetes.Namespace
  - Test.Sandwich.Contexts.Kubernetes.SeaweedFS
  - Test.Sandwich.Contexts.Kubernetes.Types
  dependencies:
  - aeson
  - bytestring
  - sandwich-contexts
  - sandwich-contexts-minio
  - containers
  - exceptions
  - filepath
  - hostname
  - http-client
  - kubernetes-client
  - kubernetes-client-core
  - lens
  - minio-hs
  - monad-logger
  - network
  - network-uri
  - process
  - random
  - regex-tdfa
  - relude
  - retry
  - safe
  - string-interpolate
  - temporary
  - text
  - unliftio
  - unliftio-core
  - vector
  - yaml

tests:
  sandwich-contexts-kubernetes-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - random
    - relude
    - sandwich
    - sandwich-contexts
    - sandwich-contexts-kubernetes
    - string-interpolate
    - unliftio
    - unliftio-core
