name: sandwich-webdriver

on:
  pull_request:
  push:

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        # - windows-latest
        ghc:
        - "8.6.5"
        - "8.8.4"
        - "8.10.7"
        - "9.0.2"
        - "9.2.8"
        - "9.4.7"
        - "9.6.3"
        - "9.8.1"
        exclude:
        - os: macOS-latest
          ghc: 8.6.5
        - os: macOS-latest
          ghc: 8.8.4

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v2
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"

    - name: Freeze
      run: |
        cd sandwich-webdriver
        cabal freeze

    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Build
      run: |
        cd sandwich-webdriver
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
        cabal build all

    - name: Test
      run: |
        cd sandwich-webdriver
        cabal test all

  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - ghc: "9.2.8"
          yaml: "stack-9.2.8.yaml"
        - ghc: "9.4.7"
          yaml: "stack-9.4.7.yaml"
        - ghc: "9.6.3"
          yaml: "stack-9.6.3.yaml"
        - ghc: "9.8.1"
          yaml: "stack-9.8.1.yaml"

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: "latest"

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.resolver }}-stack

    - name: apt
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev libxext-dev libxinerama-dev libxrandr-dev libxss-dev

    - name: Build
      run: |
        cd sandwich-webdriver
        stack build --stack-yaml ../${{matrix.yaml}} --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        cd sandwich-webdriver
        stack test --stack-yaml ../${{matrix.yaml}} --system-ghc
